name: Generate Documentations
on:
  push:
    branches: [ source ]
  schedule:
    - cron: 0 0 */2 * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16
      - run: sudo apt install -y protobuf-compiler
      - name: Generate
        run: |
          git clone https://github.com/Qv2ray/protoc-gen-doc
          cd protoc-gen-doc
          make build
          export PATH=$(pwd):$PATH
          cd ..
          git clone https://github.com/v2fly/v2ray-core
          for f in $(find ./v2ray-core/ -name "*.proto"); do mkdir -p ./protos/$(dirname $f) ; cp -v $f ./protos/$f; done
          cd ./protos/v2ray-core/
          mkdir docs/
          protoc --doc_out=docs --doc_opt=html,index.html,source_relative $(find . -name '*.proto')
      - name: GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: main
          folder: ./protos/v2ray-core/docs/
          clean: false
