# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ ci ]
  schedule:
    - cron: 0 0 */2 * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16
      - run: sudo apt install -y protobuf-compiler
      - run: |
         make build
         export PATH=$(pwd):$PATH
         git clone https://github.com/v2fly/v2ray-core
         for f in $(find ./v2ray-core/ -name "*.proto"); do mkdir -p ./protos/$(dirname $f) ; cp -v $f ./protos/$f; done
         cd ./protos/v2ray-core/
         mkdir docs/
         protoc --doc_out=docs --doc_opt=html,index.html,source_relative $(find . -name '*.proto')
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.3.0
        with:
          target_branch: main
          keep_history: true
          build_dir: ./protos/v2ray-core/docs/
